services:
  mongo:
    image: mongo
    container_name: MONGO_DB_SERVER
    restart: always
    ports:
      - ${MONGO_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  redis:
    image: redis:7.2
    container_name: REDIS_DB
    restart: always
    ports:
      - ${REDIS_PORT}:6379

