
OPERATION_SYSTEM_AGENT_NAME = "Operation_System"
PROJECT_MANAGER_AGENT_NAME = "Project_Manager"
RESEARCH_AGENT_NAME = "Research"
EVERYONE = "Everyone"
USER_NAME = "User"
SOFTWARE_ENGINEER_AGENT_NAME = "Software_Engineer"
DEVELOPER_SPECIALIST_AGENT_NAME = "Developer_Specialist"